### ISSUE TITLE
Text not readable

### ISSUE THREAD

**Issue by Darkenend** [AccraZed/YoRHA-UI-BetterDiscord#1]
On the Activity screen, some text can't be read unless you hover on.

![image](https://user-images.githubusercontent.com/34766606/55296033-6c9fc580-5414-11e9-92ad-ba717601a711.png)

**Comment by AccraZed** [comment]
I'm not sure exactly where you are, since the activity section on discord is in the process of a revamp and I'm using the newer version. If you can, add me on discord @accrazed#2710 so I can find exactly what you're talking about

**Comment by Darkenend** [comment]
It is on the Activity Section, the new one, so that's probably why.
