### ISSUE TITLE
Cant read certain text

### ISSUE THREAD

**Issue by Dashwastaken** [AccraZed/YoRHA-UI-BetterDiscord#10]
It doesnt show up like this in the download preview so im probably doing something wrong but i figured id report it anyway

![Discord_YyJilMxOes](https://user-images.githubusercontent.com/59170852/71359848-ef951d00-255b-11ea-915b-181d33a0070d.png)
![Discord_VoqpIq9tCp](https://user-images.githubusercontent.com/59170852/71359855-f459d100-255b-11ea-8f54-e5df01eeb7d3.png)

**Comment by AccraZed** [comment]
got it fixed! should be good now
