### ISSUE TITLE
the background lines go over images

### ISSUE THREAD

**Issue by maddeath** [AccraZed/YoRHA-UI-BetterDiscord#11]
the lines from the background go over images such as [this image](https://cdn.discordapp.com/attachments/83431109957783552/662124115389317142/unknown.png) being changed to [look like this](https://cdn.discordapp.com/attachments/83431109957783552/662132778124443658/unknown.png)

**Comment by AccraZed** [comment]
WHOOPS SORRY I DIDN'T SEE YOUR ISSUE EARLIER, yeah i initially intended for that to be the case but i can see how it could be inconvenient, so it's fixed now 👍
