### ISSUE TITLE
Text clipping into avatar image

### ISSUE THREAD

**Issue by jandersonthegreat** [AccraZed/YoRHA-UI-BetterDiscord#12]
https://yadi.sk/i/GhiAPEhzWJISmg
Very noticeable in messages like the one linked above, where an h is indistinguishable from an n.  Minor announce, but would like to see this fixed.  Otherwise, I love the theme!

**Comment by AccraZed** [comment]
Where exactly did you find this? Are these messages in general? cause if that's the case theres a lot more broken apparently than just that and it's from an update today or something

**Comment by jandersonthegreat** [comment]
It's all text, that's just the one that made out noticeable. It's probably due to recent changes with discord, as I didn't notice it before the update and do not have any other plugins or themes running that could change the layout

**Comment by jandersonthegreat** [comment]
Excuse me, all messages in general

**Comment by AccraZed** [comment]
mmm alright ill need to update discord when I get home and fix what might or might not be a migraine

**Comment by AccraZed** [comment]
_should_ be fixed now, at least that's how it appears for me. let me know if there's still any problems!

**Comment by joey-maldonado** [comment]
I was able to fix this issue by reinjecting EnhancedDiscord. I also had an issue where the areas around the names weren't using the right fonts which this also fixed.

**Comment by jandersonthegreat** [comment]
![image](https://user-images.githubusercontent.com/46681939/73795081-c7622600-4777-11ea-8b28-64b80f7e919d.png)
All fixed from what I can tell.  Thanks for the quick turnaround!  I'll let you close the issue
