### ISSUE TITLE
discord server doesn't display properly

### ISSUE THREAD

**Issue by Mara-Li** [AccraZed/YoRHA-UI-BetterDiscord#13]
Hello ! I try to install your theme via https://betterdiscordlibrary.com/themes/NieR%20Automata%20UI%20Theme but i think it isn't up to date. So my server doesn't appair properly. 
<img width="59" alt="image" src="https://user-images.githubusercontent.com/30244939/74664500-1f4c5400-519e-11ea-9e27-a5e137c799b1.png">

Can you help me to update this beautiful theme ? I try with the release package, but BD canno't build it :<

**Comment by AccraZed** [comment]
If youre talking about how one of the servers is square, ill look into it in a couple hours when im done with classes - if its not that, specify more, please! Tyty

**Comment by Mara-Li** [comment]
Well I try with different version, so i think my screenshot give you more information.
In fact : 
- squared icon when there is a transparent background
- icon quit the folder when folder are little

**Comment by Mara-Li** [comment]
Also, on my windows, the typo seems a little buggy : 
![image](https://user-images.githubusercontent.com/30244939/74749009-bdf1b700-5269-11ea-96e1-1d67afa2fc00.png)
(On my mac : https://cdn.discordapp.com/attachments/381443785307062285/678969995790909455/unknown.png)

**Comment by AdamEternal** [comment]
I also have the square server icons bug, same as @Mara-Li.

**Comment by AccraZed** [comment]
forgot to close - should be fixed now, but icons are just square now because I thought it was more true to the NieR theme
