### ISSUE TITLE
avatar and icons bug?

### ISSUE THREAD

**Issue by skduk** [AccraZed/YoRHA-UI-BetterDiscord#14]
a few server icons are square instead of circular, and in text chats people's avatars are square and obscure their names.
![image](https://user-images.githubusercontent.com/64236819/80166217-c62af180-8620-11ea-9387-b749b7565a62.png)
anyone know how to fix this??

**Comment by AccraZed** [comment]
God damnit, discords been being a bitch - I had issues and had to clear my cache on discord to get it to fix (%appdata%/Discord/cache) let me know if that doesn't solve it

**Comment by skduk** [comment]
that didn't seem to work, i also tried clearing all the other caches like GPUCache and CodeCache just in case

**Comment by AccraZed** [comment]
god do i fucking hate how bad i am at code i have no idea why it's like that ree

**Comment by AccraZed** [comment]
![image](https://user-images.githubusercontent.com/8460982/80175468-a74a4200-85c3-11ea-8ab1-c49fe7cf7df4.png)
it looks like this on my end, not sure why it's so fucked for you

**Comment by skduk** [comment]
i'm on windows

**Comment by skduk** [comment]
must be something on my end but i have no idea what it could be, guess i could just try reinstalling discord entirely?

**Comment by AccraZed** [comment]
maybe, ill try looking into it too. if you'd like, I can send you my exact import file too. I'm accrazed#2710 on discord
