### ISSUE TITLE
Japanese Rodin Font?

### ISSUE THREAD

**Issue by egaruK** [AccraZed/YoRHA-UI-BetterDiscord#15]
I recently found this theme as a fan of NieR Automata but also as a Japanese it is unfortunate to see that only the Latin alphabet is supported in the Rodin font, i do not know if it is a possibility to add support for the Japanese alphabet but it would be much appreciated.

**Comment by AccraZed** [comment]
Oh, yeah ill find a font online and definitely add support when I get the chance. Thanks for letting me know!



Sent from my T-Mobile 4G LTE Device



-------- Original message --------

**Comment by AccraZed** [comment]
I can't find the rodin font for japan support online. Can you send me a screenshot of how the text looks at the moment, or maybe send me a friend request at accrazed#2710 so we can get it figured out?
