### ISSUE TITLE
Server Folder background very small

### ISSUE THREAD

**Issue by marcussacana** [AccraZed/YoRHA-UI-BetterDiscord#18]
![image](https://user-images.githubusercontent.com/10576957/86504635-5d36c700-bd91-11ea-9432-1ef7ef4944b2.png)
Also, good work with this fucking theme, it's the first time that I saw a creative theme like this to discord.
This remember me, do you know if have any theme like this but to persona 5 style?

**Comment by AccraZed** [comment]
FOLDERS ARE CANCER TO WORK WITH IN CSS IM SO SORRY, KINDA HAVE TO DEAL W IT

ALSO I THOUGHT ABOUT DOING A PERSONA THEME ONCE BUT NEVER GOT AROUND TO IT, NEVER PLAYED THE GAMES SO NEVER GOT A CRAZY INSPIRATION
