### ISSUE TITLE
"Home" button at the top of server list is invisible, tooltip text when mousing over servers no longer visible

### ISSUE THREAD

**Issue by floral-qua-floral** [AccraZed/YoRHA-UI-BetterDiscord#23]
Everything was fine yesterday, so I'm assuming a discord update might've made things go wrong? Uninstalling and then reinstalling BD doesn't seem to change anything.

Missing "Home" icon:
![image](https://user-images.githubusercontent.com/49110090/112532054-bb239880-8d7e-11eb-8e9e-d900faab557e.png)

Tooltip text isn't visible:
![image](https://user-images.githubusercontent.com/49110090/112532199-eb6b3700-8d7e-11eb-9d08-45f8a159e4e4.png)

Interestingly, the tooltip is still sized correctly based on the server's name, even though the text isn't there - the tooltip for "/r/gmod" is much smaller than the tooltip for "Rivals of Aether":
![image](https://user-images.githubusercontent.com/49110090/112532349-1b1a3f00-8d7f-11eb-9ba5-a4abde9a2f15.png)

**Comment by AccraZed** [comment]
Yeah been having reports that shit is fucked, cant work on it until sunday though :CSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Floral ***@***.***> Date: 3/25/21  3:36 PM  (GMT-05:00) To: AccraZed/YoRHA-UI-BetterDiscord ***@***.***> Cc: Subscribed ***@***.***> Subject: [AccraZed/YoRHA-UI-BetterDiscord] "Home" button at the top of server list is invisible, tooltip text when mousing over servers no longer visible (#23) 
Everything was fine yesterday, so I'm assuming a discord update might've made things go wrong? Uninstalling and then reinstalling BD doesn't seem to change anything.
Missing "Home" icon:

Tooltip text isn't visible:

Interestingly, the tooltip is still sized correctly based on the server's name, even though the text isn't there - the tooltip for "/r/gmod" is much smaller than the tooltip for "Rivals of Aether":
