### ISSUE TITLE
user avatars and server icons in folders are rounded

### ISSUE THREAD

**Issue by LastExceed** [AccraZed/YoRHA-UI-BetterDiscord#28]
try to make them squared

attempts so far: 
![](https://cdn.discordapp.com/attachments/722467662411595806/846085049311952926/unknown.png)
![](https://cdn.discordapp.com/attachments/722467662411595806/846085335443570768/unknown.png)
status indicator doesnt separate from the image enough, maybe try outline?
![](https://cdn.discordapp.com/attachments/722467662411595806/847499730904154143/unknown.png)
(screenshot from BD plugin "status everywhere"

**Comment by AccraZed** [comment]
added RadialStatus, see 6c9f878a247fdf989f9c2d4926eef502f2f459eb
![image](https://user-images.githubusercontent.com/8460982/120567237-448ac300-c3df-11eb-94a1-b730f0e14336.png)
![image](https://user-images.githubusercontent.com/8460982/120567250-49e80d80-c3df-11eb-957c-0edfb3aef05c.png)
![image](https://user-images.githubusercontent.com/8460982/120567265-4eacc180-c3df-11eb-8f6f-8338acfabb08.png)
