### ISSUE TITLE
on/off switches are rounded

### ISSUE THREAD

**Issue by LastExceed** [AccraZed/YoRHA-UI-BetterDiscord#30]
![](https://i.imgur.com/9dngy0F.png)
try squared checkboxes ?
![](https://i.imgur.com/bc7DNm6.png)
(screenshot from theme "slate")

**Comment by AccraZed** [comment]
![image](https://user-images.githubusercontent.com/8460982/121782762-2c523b00-cb79-11eb-8660-6567d2a5818f.png)
I have it fixed to this for now, I don't really know how to make checkboxes for those and I don't know the benefit to using it. If you want it to happen you can open up another issue to change it C:
