### ISSUE TITLE
make user popout look more nier style

### ISSUE THREAD

**Issue by LastExceed** [AccraZed/YoRHA-UI-BetterDiscord#31]
![](https://cdn.discordapp.com/attachments/722467018368090145/845425883249377380/unknown.png)
![](https://cdn.discordapp.com/attachments/722467018368090145/845425901763428353/unknown.png)

**Comment by LastExceed** [comment]
discord default looks like this now
![](https://cdn.discordapp.com/attachments/722467018368090145/847237899794644992/unknown.png)
top is colored based on PFP

**Comment by AccraZed** [comment]
![image](https://user-images.githubusercontent.com/8460982/121786306-033ba580-cb8d-11eb-9440-833ce2a27e71.png)
upgraded popout to be more faithful, will close the issue for now but if new idas arise to improve upon it you can make a new issue C:

**Comment by LastExceed** [comment]
imo this is a downgrade, too much wasted space. also the DM textbox is missing
