### ISSUE TITLE
"active now" tiles bleed into background

### ISSUE THREAD

**Issue by LastExceed** [AccraZed/YoRHA-UI-BetterDiscord#34]
![](https://i.imgur.com/IcAyMn2.png)
maybe use same design as chat text box? 
![](https://i.imgur.com/p01fjQ8.png)
alternatively an outline could work

**Comment by LastExceed** [comment]
also text becomes unreadable on hover
![](https://i.imgur.com/ObVdXHX.png)

**Comment by AccraZed** [comment]
yeah, the whole panel was updated so I need to go ahead and fix it up, will start working on it now C:
