### ISSUE TITLE
Option to remove the Grid Overlay/Lattices?

### ISSUE THREAD

**Issue by Mangos02** [AccraZed/YoRHA-UI-BetterDiscord#4]
the grid overlay goes on everything, pictures, videos, everything, can there be a option to disable it?

**Comment by AccraZed** [comment]
I tinkered around, but I don't think I could have an option to remove the grid overlay without having to change the source .css (that I don't have the ability to change live)

HOWEVER:

you can change it in your own version using better discord's Custom CSS Editor tab, in user settings, and putting this

``#app-mount:after
{
    visibility:hidden;
}``

in there
