### ISSUE TITLE
Threads displayed as channel without but without an icon.

### ISSUE THREAD

**Issue by VargentSomnium** [AccraZed/YoRHA-UI-BetterDiscord#55]
When there is a thread active it appears under the appropriate channel however it appears to be another channel but just with out the square icon. I think this should be an easy fix using a smaller font and an indentation with some small L arrow.

**Comment by AccraZed** [comment]
All thread stuff is new and I havent had the chance to work on it. Over this upcoming weekend I'll be working to fix, though.
