### ISSUE TITLE
Some plugin incompatibilities.

### ISSUE THREAD

**Issue by The-Scout** [AccraZed/YoRHA-UI-BetterDiscord#56]
CreationDatev1.4.6by DevilBro - Text for creation date is invisible inside of the view profile menu.
ClickToChatv0.0.1by hobbica - Clicking the button does not open direct messages.
ReadAllNotificationsButtonv1.6.8by DevilBro - Button is invisible

**Comment by AccraZed** [comment]
Can you send links to the plugin repos to download? Thanks c:

**Comment by The-Scout** [comment]
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CreationDate/

https://github.com/hobbica98/ClickToChat-BetterDiscord-Plugin/blob/master/ClickToChat.plugin.js

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReadAllNotificationsButton/

There you go
