### ISSUE TITLE
broken on enhanced discord

### ISSUE THREAD

**Issue by HoneyOTU1337** [AccraZed/YoRHA-UI-BetterDiscord#6]
![image](https://user-images.githubusercontent.com/38541316/64003960-c4d21500-cae3-11e9-8a7d-edef66e3f523.png)

**Comment by AccraZed** [comment]
I'm sorry for not getting back on this earlier, but I'm not familiar with enhanced discord and it would be a pain in the ass to accommodate for these sorts of plugins or whatnot
