### ISSUE TITLE
Friends logo disappearing when clicked

### ISSUE THREAD

**Issue by Shinorax** [AccraZed/YoRHA-UI-BetterDiscord#61]
![image](https://user-images.githubusercontent.com/92134037/136490180-ab5f5ebd-4cb9-43f8-97a5-bca6edebb80a.png)
![image](https://user-images.githubusercontent.com/92134037/136490202-652c4370-e8bd-4db0-89d6-65bc4cf2f898.png)

**Comment by AccraZed** [comment]
resolved in fecd4e7
