### ISSUE TITLE
very hard to read what I'm typing

### ISSUE THREAD

**Issue by RyanLemillion** [AccraZed/YoRHA-UI-BetterDiscord#8]
is there any way to make the text in the message text box darker

**Comment by AccraZed** [comment]
not sure what you're referring to, can you send a screencap or selectors or something?

**Comment by RyanLemillion** [comment]
[](url)
![image](https://user-images.githubusercontent.com/55263597/65048203-5d142a80-d929-11e9-8021-396c62b10621.png)
