### ISSUE TITLE
Discord update messed with chat bar

### ISSUE THREAD

**Issue by Everandia** [AccraZed/YoRHA-UI-BetterDiscord#9]
Recent update made chat effectively unreadable when typing, the chat bar is also now no longer aligned correctly.  
https://imgur.com/i4cFwmL 

Temporary partial fix by posting this in custom CSS:

. .scrollableContainer-2NUZem {
  background-color: rgba(255, 255, 255, 0.3);
}

However, clipping still happens when using that fix.

**Comment by AccraZed** [comment]
fixed! you should be able to ctrl R your discord to refresh it

**Comment by Everandia** [comment]
Now meta is only found in the import version when attempting to use it for some reason. Works when applied into custom CSS however. The text is also still too light of a color to be reliably visible. 
https://i.imgur.com/aaxlWqG.png
https://i.imgur.com/nh9O7Wl.png

Sorry for the frequent reports. Theme had been working fine for months up until this discord update.

**Comment by AccraZed** [comment]
I can't seem to replicate that problem, might be on your side?

also yea tbf I've been getting lazy too with it because fuck, it's annoying having to keep this bundle of shit code up to date

**Comment by Everandia** [comment]
Seems like the discord update outright broke my Better Discord. There were no new versions or fixes, but completely wiping and re-downloading it fixed the imported version. Still no meta found for the normal one, but that's not a huge deal as long as one of them works. And yea, coding is a bit of a mess which is why I refuse to get into it. I appreciate the quick follow-up and assistance!
