### ISSUE TITLE
Grid in background overlaps the image even its in full view

### ISSUE THREAD

**Issue by Minh-Than** [accrazed/YoRHA-UI-BetterDiscord#98]
Not sure if this was an intended feature or not (or just my fault) but after clicking on an image to show full view, the background grid still shows up on top of it. I pasted `https://accrazed.github.io/YoRHA-UI-BetterDiscord/NieR-Light-Source.theme.css` into my Vencord's online theme section if that helps.

<img width="859" alt="image" src="https://github.com/user-attachments/assets/64ef09ae-f45f-4270-be46-b8fd34756c75">

Love the theme by the way, might be the best light theme that I can actually stand using.

**Comment by BreadtheRipper** [comment]
Hey! We have been actively trying to see if we can fix this but based on how the rendering of the grid works, unfortunately at this time it's intended behavior. You can expect this behavior in any kind of modal (such as videos and images opened up like you showed) as well as it'll show over streams. Temporary workaround for the streams thing is just to pop the stream out as themes don't (at least on BetterDiscord) apply to popped out windows

**Comment by Minh-Than** [comment]
No worries, I always have an option to just override the overlay's CSS so i can just not display if need be. I also realized this was asked before so very sorry about that. I'll close this issue now, thanks for replying!
